config/routes.rb
Bbs::Application.routes.draw do
  root to: "bbs_threads#index"

  resources :bbs_comments, except: [:show]

  resources :bbs_threads, except: [:destroy, :update]
  scope "bbs_threads" do
    get "destroy" => "bbs_thread#destroy", as: :destroy_bbs_thread
    post "update" => "bbs_thread#update",  as: :update_bbs_thread
  end
end

app/models/bbs_comment.rb
class BbsComment < ActiveRecord::Base
  acts_as_paranoid

  attr_accessible :bbs_thread_id, :body, :password
end

app/models/bbs_thread.rb
class BbsThread < ActiveRecord::Base
  acts_as_paranoid

  attr_accessible :password, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bbs_comments_controller.rb
class BbsCommentsController < ApplicationController
  # GET /bbs_comments
  # GET /bbs_comments.json
  def index
    @bbs_comments = BbsComment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bbs_comments }
    end
  end

  # GET /bbs_comments/1
  # GET /bbs_comments/1.json
  def show
    @bbs_comment = BbsComment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bbs_comment }
    end
  end

  # GET /bbs_comments/new
  # GET /bbs_comments/new.json
  def new
    @bbs_comment = BbsComment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bbs_comment }
    end
  end

  # GET /bbs_comments/1/edit
  def edit
    @bbs_comment = BbsComment.find(params[:id])
  end

  # POST /bbs_comments
  # POST /bbs_comments.json
  def create
    @bbs_comment = BbsComment.new(params[:bbs_comment])

    respond_to do |format|
      if @bbs_comment.save
        format.html { redirect_to @bbs_comment, notice: 'Bbs comment was successfully created.' }
        format.json { render json: @bbs_comment, status: :created, location: @bbs_comment }
      else
        format.html { render action: "new" }
        format.json { render json: @bbs_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bbs_comments/1
  # PUT /bbs_comments/1.json
  def update
    @bbs_comment = BbsComment.find(params[:id])

    respond_to do |format|
      if @bbs_comment.update_attributes(params[:bbs_comment])
        format.html { redirect_to @bbs_comment, notice: 'Bbs comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bbs_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bbs_comments/1
  # DELETE /bbs_comments/1.json
  def destroy
    @bbs_comment = BbsComment.find(params[:id])
    @bbs_comment.destroy

    respond_to do |format|
      format.html { redirect_to bbs_comments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/bbs_threads_controller.rb
class BbsThreadsController < ApplicationController
  def index
    @bbs_threads = BbsThread.order("id DESC")
  end

  def show
    @bbs_thread = BbsThread.find(params[:id])
  end

  def new
    @bbs_thread = BbsThread.new
  end

  def edit
    @bbs_thread = BbsThread.find(params[:id])
  end

  def create
    @bbs_thread = BbsThread.new(params[:bbs_thread])


    redirect_to root_path and return if @bbs_thread.save
    render action: "new"
  end

  def update
    @bbs_thread = BbsThread.find(params[:id])
    redirect_to root_path and return if @bbs_thread.update_attributes(params[:bbs_thread])
    render action: "edit"
  end

  def destroy
    @bbs_thread = BbsThread.find(params[:id])
    @bbs_thread.destroy

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bbs_comments_helper.rb
module BbsCommentsHelper
end

app/helpers/bbs_threads_helper.rb
module BbsThreadsHelper
end

app/views/bbs_comments/_form.html.erb
<%= form_for(@bbs_comment) do |f| %>
  <% if @bbs_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bbs_comment.errors.count, "error") %> prohibited this bbs_comment from being saved:</h2>

      <ul>
      <% @bbs_comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bbs_thread_id %><br />
    <%= f.number_field :bbs_thread_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_field :body %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bbs_comments/edit.html.erb
<h1>Editing bbs_comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @bbs_comment %> |
<%= link_to 'Back', bbs_comments_path %>

app/views/bbs_comments/index.html.erb
<h1>Listing bbs_comments</h1>

<table>
  <tr>
    <th>Bbs thread</th>
    <th>Body</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bbs_comments.each do |bbs_comment| %>
  <tr>
    <td><%= bbs_comment.bbs_thread_id %></td>
    <td><%= bbs_comment.body %></td>
    <td><%= bbs_comment.password %></td>
    <td><%= link_to 'Show', bbs_comment %></td>
    <td><%= link_to 'Edit', edit_bbs_comment_path(bbs_comment) %></td>
    <td><%= link_to 'Destroy', bbs_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bbs comment', new_bbs_comment_path %>

app/views/bbs_comments/new.html.erb
<h1>New bbs_comment</h1>

<%= render 'form' %>

<%= link_to 'Back', bbs_comments_path %>

app/views/bbs_threads/_form.html.erb
<%= form_for(@bbs_thread) do |f| %>
  <% if @bbs_thread.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bbs_thread.errors.count, "error") %> prohibited this bbs_thread from being saved:</h2>

      <ul>
      <% @bbs_thread.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bbs_threads/edit.html.erb
<h1>Editing bbs_thread</h1>

<%= render 'form' %>

<%= link_to 'Show', @bbs_thread %> |
<%= link_to 'Back', bbs_threads_path %>

app/views/bbs_threads/index.html.erb
<h1>Listing bbs_threads</h1>

<table>
  <tr>
    <th>id</th>
    <th>title</th>
    <th></th>
    <th></th>
  </tr>

<% @bbs_threads.each do |bbs_thread| %>
  <tr>
    <td><%= bbs_thread.id %></td>
    <td><%= link_to(bbs_thread.title_string, bbs_thread) %></td>
    <td><%= link_to 'Edit', edit_bbs_thread_path(bbs_thread) %></td>
    <td><%= link_to 'Destroy', destroy_bbs_thread_path(bbs_thread) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bbs thread', new_bbs_thread_path %>

app/views/bbs_threads/new.html.erb
<h1>New bbs_thread</h1>

<%= render 'form' %>

<%= link_to 'Back', bbs_threads_path %>

app/views/bbs_threads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @bbs_thread.title %>
</p>

<p>
  <b>Password:</b>
  <%= @bbs_thread.password %>
</p>


<%= link_to 'Edit', edit_bbs_thread_path(@bbs_thread) %> |
<%= link_to 'Back', bbs_threads_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bbs</title>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>